spring:
  config:
    import:
      - email.properties
  ##############################################
  #  Springboot Mail
  ############################################
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email.spring.mail.username}
    password: ${email.spring.mail.password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  datasource:
    url: jdbc:mysql://localhost:33356/atmdb
    username: atm
    password: point
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379

jwt:
  signing:
    key: keykeykeykjadfklqwdjkqwdjknnqdjkwkjlcqwjnisijsdvjiovjiosdvjio

atm:
  notification:
    amount: 1000000